"""
Validate + report on CommonOcean scenario XML files generated by
ais_pipeline.py, for training an imitation-learning DiT.

Two kinds of checks, matching the two ways a dataset can be "not good enough":

  INTEGRITY  -- does the data represent physically/structurally valid
                scenarios at all (catches bugs in the generation pipeline --
                broken time steps, NaNs, implausible kinematics, obstacles
                that still overlap despite the collision filter)

  ADEQUACY   -- assuming the data is valid, is there ENOUGH of the RIGHT
                KIND of it for a DiT to actually learn from (speed/turn-rate
                coverage, encounter-type coverage, trajectory-length
                consistency, a difficulty baseline to beat)

Usage:
    python validate_scenerios.py generated_scenarios/ \
        --manifest manifest.jsonl \
        --report-json report.json \
        --plots-dir plots/ \
        --fixed-seq-len 20

Geographic/temporal coverage and leak-safe train/val/test splitting need a
manifest (scenario_id -> origin lat/lon, time window, contributing MMSIs) --
the CommonOcean XML itself doesn't retain real-world coordinates or vessel
identity (obstacle_id is a scenario-local integer, not the MMSI). See the
`log_manifest_entries` snippet at the bottom of this file for what to add to
ais_pipeline.py's generate_dataset_from_ais to produce one. Without a
manifest, this script still runs -- it just can't report on that slice.
"""

import argparse
import glob
import json
import math
import os
from collections import Counter, defaultdict

import numpy as np

from commonocean.common.file_reader import CommonOceanFileReader

PHYSICAL_LIMITS = dict(
    max_speed_ms=25.0,      # ~48 knots -- generous upper bound for any surface vessel
    max_accel_ms2=2.0,      # generous
    min_length_m=2.0, max_length_m=450.0,
    min_width_m=1.0, max_width_m=70.0,
)


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def load_scenario(xml_path):
    """Returns (dt, {obstacle_id: {type, length, width, depth, states}}, shallows)
    where shallows is a list of (waters_id, vertex_list, depth)."""
    scenario, _ = CommonOceanFileReader(xml_path).open()
    obstacles = {}
    for do in scenario.dynamic_obstacles:
        states = [do.initial_state] + list(do.prediction.trajectory.state_list)
        rows = []
        for s in states:
            rows.append(dict(
                time_step=s.time_step,
                x=float(s.position[0]), y=float(s.position[1]),
                orientation=float(s.orientation),
                velocity=float(getattr(s, 'velocity', float('nan'))),
                velocity_y=float(getattr(s, 'velocity_y', 0.0)),
                yaw_rate=float(getattr(s, 'yaw_rate', float('nan'))),
            ))
        obstacles[do.obstacle_id] = dict(
            type=do.obstacle_type.value,
            length=float(do.obstacle_shape.length),
            width=float(do.obstacle_shape.width),
            depth=float(do.depth) if do.depth not in (None, float('inf')) else None,
            states=rows,
        )
    shallows = [(sh.waters_id, [tuple(p) for p in sh.shape.vertices], float(sh.depth))
                for sh in scenario.shallows]
    return float(scenario.dt), obstacles, shallows


# ---------------------------------------------------------------------------
# INTEGRITY checks -- per scenario
# ---------------------------------------------------------------------------

def check_integrity(dt, obstacles, min_trajectory_len=None, fixed_seq_len=None):
    issues = []
    if len(obstacles) < 2:
        issues.append(f"only {len(obstacles)} dynamic obstacle(s) -- not a multi-vessel scene")

    for oid, obs in obstacles.items():
        states = obs['states']

        steps = [s['time_step'] for s in states]
        if steps != list(range(steps[0], steps[0] + len(steps))):
            issues.append(f"obstacle {oid}: non-consecutive time steps ({steps})")

        if fixed_seq_len is not None and len(states) != fixed_seq_len:
            issues.append(f"obstacle {oid}: {len(states)} frames, expected exactly {fixed_seq_len}")
        elif min_trajectory_len is not None and len(states) < min_trajectory_len:
            issues.append(f"obstacle {oid}: {len(states)} frames < minimum {min_trajectory_len}")

        if not (PHYSICAL_LIMITS['min_length_m'] <= obs['length'] <= PHYSICAL_LIMITS['max_length_m']):
            issues.append(f"obstacle {oid}: implausible length {obs['length']}m")
        if not (PHYSICAL_LIMITS['min_width_m'] <= obs['width'] <= PHYSICAL_LIMITS['max_width_m']):
            issues.append(f"obstacle {oid}: implausible width {obs['width']}m")

        for i, s in enumerate(states):
            vals = [s['x'], s['y'], s['orientation'], s['velocity'], s['velocity_y'], s['yaw_rate']]
            if any(math.isnan(v) or math.isinf(v) for v in vals):
                issues.append(f"obstacle {oid}: NaN/Inf at frame {i}")
                continue
            speed = math.hypot(s['velocity'], s['velocity_y'])
            if speed > PHYSICAL_LIMITS['max_speed_ms']:
                issues.append(f"obstacle {oid}: implausible speed {speed:.1f} m/s at frame {i}")
            if i > 0:
                prev = states[i - 1]
                dt_frames = s['time_step'] - prev['time_step']
                if dt_frames <= 0:
                    continue
                implied_speed = math.hypot(s['x'] - prev['x'], s['y'] - prev['y']) / (dt_frames * dt)
                if abs(implied_speed - speed) > max(3.0, 0.5 * speed):
                    issues.append(f"obstacle {oid}: frame {i} implied speed {implied_speed:.1f} m/s "
                                  f"vs stored {speed:.1f} m/s -- possible resampling artifact")
                accel = abs(speed - math.hypot(prev['velocity'], prev['velocity_y'])) / (dt_frames * dt)
                if accel > PHYSICAL_LIMITS['max_accel_ms2']:
                    issues.append(f"obstacle {oid}: implausible accel {accel:.2f} m/s^2 at frame {i}")

    return issues


def check_no_overlaps(obstacles):
    """Independent re-check with bounding CIRCLES (radius = half the hull
    diagonal): looser than the pipeline's own rectangle/CPA check on
    purpose, so a flag here is a "worth a look" signal, not proof of a real
    overlap -- but it should essentially never fire if the collision filter
    is working."""
    issues = []
    items = list(obstacles.items())
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            oid1, obs1 = items[i]
            oid2, obs2 = items[j]
            r1 = math.hypot(obs1['length'], obs1['width']) / 2.0
            r2 = math.hypot(obs2['length'], obs2['width']) / 2.0
            s1_by_t = {s['time_step']: s for s in obs1['states']}
            s2_by_t = {s['time_step']: s for s in obs2['states']}
            for t in set(s1_by_t) & set(s2_by_t):
                d = math.hypot(s1_by_t[t]['x'] - s2_by_t[t]['x'], s1_by_t[t]['y'] - s2_by_t[t]['y'])
                if d < (r1 + r2):
                    issues.append(f"obstacles {oid1}&{oid2}: bounding circles overlap at t={t} (d={d:.1f}m)")
                    break
    return issues


def check_grounding(obstacles, shallows):
    """Flags any obstacle whose trajectory enters a Shallow polygon whose
    depth is less than that obstacle's own depth (draft). Self-contained --
    uses only what's already in the scenario XML (Shallow.depth and
    DynamicObstacle.depth), no separate bathymetry file needed. Uses each
    shallow's axis-aligned bounding box rather than exact point-in-polygon,
    which is exact for the small rectangular cells ais_pipeline.py emits but
    an approximation (slightly permissive) for irregular shallow shapes."""
    issues = []
    if not shallows:
        return issues
    shallow_boxes = []
    for wid, shape, depth in shallows:
        xs = [p[0] for p in shape]
        ys = [p[1] for p in shape]
        shallow_boxes.append((min(xs), max(xs), min(ys), max(ys), depth, wid))

    for oid, obs in obstacles.items():
        draft = obs.get('depth')
        if draft is None:
            continue
        for s in obs['states']:
            for xmin, xmax, ymin, ymax, depth, wid in shallow_boxes:
                if xmin <= s['x'] <= xmax and ymin <= s['y'] <= ymax and depth < draft:
                    issues.append(f"obstacle {oid}: draft {draft}m in shallow {wid} "
                                  f"(depth {depth}m) at t={s['time_step']}")
                    break
            else:
                continue
            break
    return issues


# ---------------------------------------------------------------------------
# ADEQUACY metrics -- dataset-level
# ---------------------------------------------------------------------------

def classify_encounter(obs1, obs2, max_range_m=500.0):
    """Rough COLREGS-style label (head_on / crossing / overtaking / other)
    at the pair's closest shared approach. A heuristic for AUDITING
    encounter-type coverage in the dataset -- not a navigation-grade
    classifier, don't use it for anything safety-critical."""
    s1_by_t = {s['time_step']: s for s in obs1['states']}
    s2_by_t = {s['time_step']: s for s in obs2['states']}
    shared = sorted(set(s1_by_t) & set(s2_by_t))
    if len(shared) < 2:
        return None

    best_t, best_d = None, float('inf')
    for t in shared:
        s1, s2 = s1_by_t[t], s2_by_t[t]
        d = math.hypot(s1['x'] - s2['x'], s1['y'] - s2['y'])
        if d < best_d:
            best_d, best_t = d, t
    if best_d > max_range_m:
        return None

    s1, s2 = s1_by_t[best_t], s2_by_t[best_t]
    heading_diff = abs(((s1['orientation'] - s2['orientation'] + math.pi) % (2 * math.pi)) - math.pi)
    bearing_1to2 = math.atan2(s2['y'] - s1['y'], s2['x'] - s1['x'])
    relative_bearing = abs(((bearing_1to2 - s1['orientation'] + math.pi) % (2 * math.pi)) - math.pi)

    if heading_diff > math.radians(150):
        return 'head_on'
    if heading_diff < math.radians(30) and relative_bearing > math.radians(112.5):
        return 'overtaking'
    if math.radians(30) <= heading_diff <= math.radians(150):
        return 'crossing'
    return 'other'


def constant_velocity_baseline(all_scenarios, horizon_frames=10):
    """For each trajectory, extrapolate the last-known velocity forward and
    measure ADE/FDE against what actually happened. If a trained DiT can't
    beat this comfortably on held-out data, it isn't learning anything a
    kinematic extrapolator doesn't already give you for free -- treat it as
    a floor, not a target."""
    ade_list, fde_list = [], []
    for dt, obstacles in all_scenarios:
        for obs in obstacles.values():
            states = obs['states']
            if len(states) < horizon_frames + 2:
                continue
            anchor = states[-horizon_frames - 1]
            vx = anchor['velocity'] * math.cos(anchor['orientation']) - anchor['velocity_y'] * math.sin(anchor['orientation'])
            vy = anchor['velocity'] * math.sin(anchor['orientation']) + anchor['velocity_y'] * math.cos(anchor['orientation'])
            errors = []
            for k in range(1, horizon_frames + 1):
                actual = states[-horizon_frames - 1 + k]
                pred_x = anchor['x'] + vx * k * dt
                pred_y = anchor['y'] + vy * k * dt
                errors.append(math.hypot(pred_x - actual['x'], pred_y - actual['y']))
            ade_list.append(float(np.mean(errors)))
            fde_list.append(errors[-1])
    return dict(
        constant_velocity_ADE_m=float(np.mean(ade_list)) if ade_list else None,
        constant_velocity_FDE_m=float(np.mean(fde_list)) if fde_list else None,
        n_trajectories_evaluated=len(ade_list),
    )


def normalization_stats(all_scenarios):
    """Per-channel mean/std/min/max -- needed to normalize inputs before
    diffusion noise is applied, and a good outlier check in its own right
    (a wildly large std usually means one bad trajectory, not real variance)."""
    channels = defaultdict(list)
    for dt, obstacles in all_scenarios:
        for obs in obstacles.values():
            for s in obs['states']:
                for k in ('x', 'y', 'orientation', 'velocity', 'velocity_y', 'yaw_rate'):
                    channels[k].append(s[k])
    return {k: dict(mean=float(np.mean(v)), std=float(np.std(v)),
                     min=float(np.min(v)), max=float(np.max(v)))
            for k, v in channels.items()}


def aggregate_adequacy(all_scenarios):
    speeds, yaw_rates, traj_lengths = [], [], []
    obstacle_type_counts = Counter()
    agents_per_scenario = []
    encounter_counts = Counter()

    for dt, obstacles in all_scenarios:
        agents_per_scenario.append(len(obstacles))
        for obs in obstacles.values():
            obstacle_type_counts[obs['type']] += 1
            traj_lengths.append(len(obs['states']))
            for s in obs['states']:
                speeds.append(math.hypot(s['velocity'], s['velocity_y']))
                yaw_rates.append(s['yaw_rate'])

        items = list(obstacles.values())
        for i in range(len(items)):
            for j in range(i + 1, len(items)):
                label = classify_encounter(items[i], items[j])
                if label:
                    encounter_counts[label] += 1

    speeds, yaw_rates, traj_lengths = np.array(speeds), np.array(yaw_rates), np.array(traj_lengths)
    return dict(
        n_scenarios=len(all_scenarios),
        n_trajectories=len(traj_lengths),
        agents_per_scenario=dict(mean=float(np.mean(agents_per_scenario)),
                                  min=int(np.min(agents_per_scenario)),
                                  max=int(np.max(agents_per_scenario))) if agents_per_scenario else {},
        trajectory_length_frames=dict(mean=float(np.mean(traj_lengths)),
                                       p5=float(np.percentile(traj_lengths, 5)),
                                       p50=float(np.percentile(traj_lengths, 50)),
                                       p95=float(np.percentile(traj_lengths, 95))) if len(traj_lengths) else {},
        obstacle_type_counts=dict(obstacle_type_counts),
        speed_ms=dict(mean=float(np.mean(speeds)), p50=float(np.percentile(speeds, 50)),
                      p95=float(np.percentile(speeds, 95))) if len(speeds) else {},
        pct_maneuvering_frames=float(np.mean(np.abs(yaw_rates) > 0.02) * 100) if len(yaw_rates) else 0.0,
        encounter_type_counts=dict(encounter_counts),
    )


# ---------------------------------------------------------------------------
# Manifest (optional -- geographic/temporal coverage, leak-safe splitting)
# ---------------------------------------------------------------------------

def manifest_report(manifest_path):
    entries = [json.loads(line) for line in open(manifest_path)]
    unique_mmsis = set()
    for e in entries:
        unique_mmsis.update(e.get('mmsis', []))
    t_starts = sorted(e['t_start'] for e in entries)
    return dict(
        n_manifest_entries=len(entries),
        unique_vessels_seen=len(unique_mmsis),
        time_range=(t_starts[0], t_starts[-1]) if t_starts else None,
        unique_origin_cells=len({(round(e['origin_lat'], 2), round(e['origin_lon'], 2)) for e in entries}),
    )


# ---------------------------------------------------------------------------
# Plots (best-effort -- skipped cleanly if matplotlib isn't installed)
# ---------------------------------------------------------------------------

def save_plots(all_scenarios, out_dir):
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed -- skipping plots (pip install matplotlib to enable).")
        return

    os.makedirs(out_dir, exist_ok=True)
    speeds, yaw_rates, traj_lengths = [], [], []
    for dt, obstacles in all_scenarios:
        for obs in obstacles.values():
            traj_lengths.append(len(obs['states']))
            for s in obs['states']:
                speeds.append(math.hypot(s['velocity'], s['velocity_y']))
                yaw_rates.append(s['yaw_rate'])

    for name, data, xlabel in [('speed', speeds, 'speed (m/s)'),
                                ('yaw_rate', yaw_rates, 'yaw rate (rad/s)'),
                                ('trajectory_length', traj_lengths, 'frames')]:
        plt.figure()
        plt.hist(data, bins=40)
        plt.xlabel(xlabel)
        plt.ylabel('count')
        plt.title(f'{name} distribution')
        plt.savefig(os.path.join(out_dir, f'{name}_hist.png'), dpi=120, bbox_inches='tight')
        plt.close()
    print(f"Saved plots to {out_dir}/")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('scenario_dir')
    ap.add_argument('--manifest', default=None)
    ap.add_argument('--report-json', default=None)
    ap.add_argument('--plots-dir', default=None)
    ap.add_argument('--min-trajectory-len', type=int, default=None)
    ap.add_argument('--fixed-seq-len', type=int, default=None)
    ap.add_argument('--max-issues-printed', type=int, default=20)
    args = ap.parse_args()

    paths = sorted(glob.glob(os.path.join(args.scenario_dir, '*.xml')))
    if not paths:
        print(f"No .xml files found in {args.scenario_dir}")
        return

    all_scenarios = []
    all_issues = []
    n_parse_failures = 0
    for path in paths:
        try:
            dt, obstacles, shallows = load_scenario(path)
        except Exception as exc:
            n_parse_failures += 1
            all_issues.append(f"{os.path.basename(path)}: FAILED TO PARSE -- {exc}")
            continue
        issues = check_integrity(dt, obstacles, args.min_trajectory_len, args.fixed_seq_len)
        issues += check_no_overlaps(obstacles)
        issues += check_grounding(obstacles, shallows)
        for issue in issues:
            all_issues.append(f"{os.path.basename(path)}: {issue}")
        all_scenarios.append((dt, obstacles))

    adequacy = aggregate_adequacy(all_scenarios)
    norm_stats = normalization_stats(all_scenarios)
    baseline = constant_velocity_baseline(all_scenarios)

    print("=" * 70)
    print(f"Scanned {len(paths)} files ({n_parse_failures} failed to parse)")
    print(f"Integrity issues found: {len(all_issues)}")
    for issue in all_issues[:args.max_issues_printed]:
        print("  -", issue)
    if len(all_issues) > args.max_issues_printed:
        print(f"  ... and {len(all_issues) - args.max_issues_printed} more")

    print("\n--- Adequacy ---")
    print(f"scenarios: {adequacy['n_scenarios']}   trajectories: {adequacy['n_trajectories']}")
    print(f"agents/scenario: {adequacy.get('agents_per_scenario')}")
    print(f"trajectory length (frames): {adequacy.get('trajectory_length_frames')}")
    print(f"speed (m/s): {adequacy.get('speed_ms')}")
    print(f"% frames maneuvering (|yaw_rate| > ~1 deg/s): {adequacy['pct_maneuvering_frames']:.1f}%")
    print(f"obstacle types: {adequacy['obstacle_type_counts']}")
    print(f"encounter types (heuristic): {adequacy['encounter_type_counts']}")

    print("\n--- Constant-velocity baseline (floor to beat) ---")
    print(baseline)

    print("\n--- Normalization stats ---")
    for k, v in norm_stats.items():
        print(f"  {k}: {v}")

    if args.manifest and os.path.exists(args.manifest):
        print("\n--- Manifest coverage ---")
        print(manifest_report(args.manifest))
    else:
        print("\n(no --manifest supplied -- skipping geographic/temporal coverage and "
              "leak-safe split checks; see the docstring at the top of this file)")

    report = dict(n_files=len(paths), n_parse_failures=n_parse_failures,
                  n_integrity_issues=len(all_issues), issues=all_issues,
                  adequacy=adequacy, constant_velocity_baseline=baseline,
                  normalization_stats=norm_stats)
    if args.report_json:
        with open(args.report_json, 'w') as f:
            json.dump(report, f, indent=2)
        print(f"\nWrote full report to {args.report_json}")

    if args.plots_dir:
        save_plots(all_scenarios, args.plots_dir)


if __name__ == "__main__":
    main()


# ---------------------------------------------------------------------------
# Add this to ais_pipeline.py's generate_dataset_from_ais to get a manifest
# (append near where `stats['scenarios_written'] += 1` happens, and write
# `manifest_entries` to a .jsonl file at the end of the function):
#
#   manifest_entries.append(dict(
#       scenario_id=f"scenario_{scenario_counter:04d}",
#       t_start=str(t_start), t_end=str(t_end),
#       origin_lat=origin_lat, origin_lon=origin_lon,
#       mmsis=sorted(int(m) for m in current_fleet),
#       n_vessels=n_obstacles_added,
#   ))
#   ...
#   with open("manifest.jsonl", "w") as f:
#       for e in manifest_entries:
#           f.write(json.dumps(e) + "\n")
# ---------------------------------------------------------------------------